### ISSUE TITLE
`TypeError: Cannot read properties of undefined` when trying to run on remote vscode (using gitpod.io)

### ISSUE THREAD

**Issue by rolandoam** [diffbot/code-gpt-docs#358]
When adding the extension on a remote vscode (I have not seen this happen on regular vscode), I get the following error:

```
2024-08-22 17:45:46.884 [error] Activating extension DanielSanMedium.dscodegpt failed due to an error:
2024-08-22 17:45:46.884 [error] TypeError: Cannot read properties of undefined (reading 'toLowerCase')
	at NWe (/workspace/.vscode-remote/extensions/danielsanmedium.dscodegpt-3.4.38-universal/dist/extension.js:704:16739)
	at sRe (/workspace/.vscode-remote/extensions/danielsanmedium.dscodegpt-3.4.38-universal/dist/extension.js:710:1934)
	at async m.n (/ide/out/vs/workbench/api/node/extensionHostProcess.js:144:6409)
	at async m (/ide/out/vs/workbench/api/node/extensionHostProcess.js:144:6372)
	at async m.l (/ide/out/vs/workbench/api/node/extensionHostProcess.js:144:5829)
```

An easy way to repro is to:

* get a free account on gitpod.io
* create a new workspace
* install codegpt

You can look at the output labeled as "Extension Host (remote)"

**Comment by PilarHidalgo** [comment]
@rolandoam, Could you share the details of your server? OS, VSCode version, the conexion (vpn or not).

**Comment by rolandoam** [comment]
@PilarHidalgo linux (running on a VM), VSCode 1.92.1, no vpn

I can also share a workspace (vm) with you if that makes it easier to debug.

**Comment by carlospaiva** [comment]
@PilarHidalgo I face the same issue with VS Codium on Mac OS.

Version: 1.93.1
Release: 24256
Commit: dbab3f8e8c5da7ca1bde636806e0a973e497aa01
Date: 2024-09-12T18:31:21.769Z
Electron: 30.4.0
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 22.6.0

**Comment by codegpt-support** [comment]
🙏 Sorry for the delay in getting back to you and thanks for your patience.

We’ve been working on improving compatibility with different environments (including remote VS Code setups) and have released new versions of the extension since this issue was opened.

👉 We invite you to update to the latest version of CodeGPT (currently 3.14.118) and check if the problem persists.

If after updating you still see the same behavior, please let us know here with your environment details (VS Code/VSCodium version, OS, extension version). That will help us confirm if the fix fully covers your case or if we need to escalate further.

Thanks again for reporting and helping us improve!

**Comment by codegpt-netizen** [comment]
Closing as stale: this was reported against a 2024 build and we asked for a retest on a current version in October 2025 without a reply. Remote setups are exercised regularly now. If it still happens on 3.24.64, please open a new issue with the activation error.
